-- Crear secuencias para los IDs autoincrementales
CREATE SEQUENCE seq_categoria START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_presupuesto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_metodopago START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cuenta START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_movimiento START WITH 1 INCREMENT BY 1;
